name: llm_gat_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - jupyterlab-lsp
  - python-lsp-server
  - boto3
  - pip
  - tqdm
  - git
  - pre-commit
  - requests
  - beautifulsoup4
  - graphviz
  - pydot
  - sympy
  - ffmpeg
  - qrcode
  - matplotlib
  - pillow
  - pdf2image
  - ipywidgets
  - pandas
  - lxml
  - duckdb
  - pillow
  - tabulate
  - coverage
  - pytest
  - pytest-timeout
  - pypdf
  - pip:
      - gradio
      - anthropic
      - openai
      - markitdown[all]
      - fastmcp
      - praat-parselmouth
