name: llm_gat_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - jupyterlab-lsp
  - python-lsp-server
  - boto3
  - pip
  - tqdm
  - pre-commit
  - graphviz
  - pydot
  - sympy
  - ffmpeg
  - qrcode
  - matplotlib
  - ipywidgets
  - pandas
  - lxml
  - duckdb
  - pillow
  - tabulate
  - coverage
  - pytest
  - pip:
      - gradio
      - anthropic
      - openai
